# Generated by Django 5.1.6 on 2025-03-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_orders_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
